services:
  - type: web
    name: portfolio
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
